//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftLegion.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftLegion.Common.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string Entity_CreationDate {
            get {
                return ResourceManager.GetString("Entity_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активен.
        /// </summary>
        public static string Entity_IsActive {
            get {
                return ResourceManager.GetString("Entity_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата последнего изменения.
        /// </summary>
        public static string Entity_LastModifiedDate {
            get {
                return ResourceManager.GetString("Entity_LastModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приносим свои извинения. Произошла непредвиденная ошибка во время обрабоки запроса..
        /// </summary>
        public static string Error_WhileProcessingRequest {
            get {
                return ResourceManager.GetString("Error_WhileProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление.
        /// </summary>
        public static string Log_Action_Create {
            get {
                return ResourceManager.GetString("Log_Action_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление.
        /// </summary>
        public static string Log_Action_Delete {
            get {
                return ResourceManager.GetString("Log_Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование.
        /// </summary>
        public static string Log_Action_Update {
            get {
                return ResourceManager.GetString("Log_Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFGHIJKLMNOPQRSTUVWXYZ.
        /// </summary>
        public static string Misc_EnglishLettersCapital {
            get {
                return ResourceManager.GetString("Misc_EnglishLettersCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка валидации..
        /// </summary>
        public static string Validation_Error {
            get {
                return ResourceManager.GetString("Validation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение {0} не может быть больше {1}..
        /// </summary>
        public static string Validation_FromToInvalid {
            get {
                return ResourceManager.GetString("Validation_FromToInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение не является датой..
        /// </summary>
        public static string Validation_InvalidDateTime {
            get {
                return ResourceManager.GetString("Validation_InvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка не соответсвует формату GUID..
        /// </summary>
        public static string Validation_InvalidGuidString {
            get {
                return ResourceManager.GetString("Validation_InvalidGuidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение не является булевым..
        /// </summary>
        public static string Validation_InvalidPropertyNotBool {
            get {
                return ResourceManager.GetString("Validation_InvalidPropertyNotBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип поля модели {0} - не поддерживает сравнения..
        /// </summary>
        public static string Validation_NotIComparable {
            get {
                return ResourceManager.GetString("Validation_NotIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИНН для нерезидентов РУз не должно превышать 20 символов..
        /// </summary>
        public static string Validation_NotResidentInnInvalid {
            get {
                return ResourceManager.GetString("Validation_NotResidentInnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИНН для резидентов РУз не должно быть строго 9-ть символов..
        /// </summary>
        public static string Validation_ResidentInnInvalid {
            get {
                return ResourceManager.GetString("Validation_ResidentInnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестное поле модели {0}..
        /// </summary>
        public static string Validation_UnknowPropery {
            get {
                return ResourceManager.GetString("Validation_UnknowPropery", resourceCulture);
            }
        }
    }
}
